version: 2
jobs:
 trade:
   machine: true
   steps:
     - checkout
     - run:
           name: "Build trade analysis container"
           command: |
            docker build -f Dockerfile.trade -t cmzambranat/trade .
     - deploy:
           name: "Push to Docker Hub"
           command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
                docker push cmzambranat/trade
              fi
workflows:
   version: 2
   commit:
     jobs:
       - trade