version: 2
jobs:
 meta:
   machine: true
   steps:
     - checkout
     - run:
           name: "Build Meta analysis Container"
           command: |
            docker build -f Dockerfile.meta -t cmzambranat/meta .
     - deploy:
           name: "Push to Docker Hub"
           command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
                docker push cmzambranat/meta
              fi
workflows:
   version: 2
   commit:
     jobs:
       - meta